dist:     xenial
sudo:     required

language: c

os: linux

compiler: gcc

env:
  global:
    - CODECOV_TOKEN="64172ad9-b384-4379-a529-28823530357f"

install:
    - sudo apt-get update
    - sudo apt-get install cppcheck
    - sudo apt-get install valgrind
    - sudo apt-get install clang-format
    - sudo apt-get install lcov
    - sudo apt-get install libstdc++6
    - sudo apt-get install cmake
    # Google tests
    - sudo apt-get install libgtest-dev
    - cd /usr/src/gtest
    - sudo cmake .
    - sudo make
    - sudo cp *.a /usr/lib
    - cd -

before_script:
    - cd project/DynArray
    - clang-format -i -style=Google *.h *.cpp *.c
    - cd -
    - cd project/linear
    - clang-format -i -style=Google *.h *.cpp *.c
    - cd -
    - cd project/processes
    - clang-format -i -style=Google *.h *.cpp *.c
    - cd -
    - cd project/threads
    - clang-format -i -style=Google *.h *.cpp *.c
    - cd -
    - cppcheck --quiet --error-exitcode=1 --force . || travis_terminate 1
    - ./linters/run.sh || travis_terminate 1

script:
    - cmake .
    - make || travis_terminate 1
    - valgrind --tool=memcheck --show-leak-kinds=all --leak-resolution=med  --track-origins=yes ./test_linear.out || travis_terminate 1
    - valgrind --tool=memcheck --show-leak-kinds=all --leak-resolution=med  --track-origins=yes ./test_threads.out || travis_terminate 1
    - valgrind --tool=memcheck --show-leak-kinds=all --leak-resolution=med  --track-origins=yes ./test_DynArray.out || travis_terminate 1
#    - valgrind --tool=memcheck --show-leak-kinds=all --leak-resolution=med  --track-origins=yes ./test_processes.out || travis_terminate 1
after_script:
    - lcov —capture —directory ./CMakeFiles/task_library.dir/project/src —output-file coverage.info
    - bash <(curl -s https://codecov.io/bash)
    - make clean