dist:     trusty    # используем Ubuntu 14.04 Trusty Tahr (а не 12.02 Precise Pangolin)
sudo:     required  # используем Virtual Machine (а не Docker container)

language: c

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

env:
    - sudo apt-get update
    - sudo apt-get install valgrind
    - sudo apt-get install libstdc++6
    - sudo apt-get install cmake
    # список переменных окружения, влияющих на матрицу сборки:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

script:
    - cmake .
    - make
#    - cmake --build .
#    - ctest .
    - valgrind --tool=memcheck --leak-check=full --leak-resolution=med  --track-origins=yes ./tests.out
